try:
    from tkinter import *
    from time import sleep
except ImportError:
    print("Per poter eseguire queto file, installare le librerie:")
    print("tkinter [pip install tkinter]")
    print("time [pip instal time]")


def gettone():
    global nome, squadriglia, specialita, primo, secondo, terzo, tappa, carattere, salute, aiuto
    nomefileprimitivo = nomefilep.get()
    nomefile = nomefileprimitivo + ".csv"
    nome = nomep.get()
    squadriglia = squadrigliap.get()
    specialita = specialitap.get()
    primo = primop.get()
    secondo = secondop.get()
    terzo = terzop.get()
    tappa = tappap.get()
    carattere = caratterep.get()
    salute = salutep.get()
    aiuto = aiutop.get()
    try:
        out_file = open(nomefile, "a")
        out_file.write(nome)
        out_file.write("; ")
        out_file.write(squadriglia)
        out_file.write("; ")
        out_file.write("SPECIALITA")
        out_file.write("; ")
        out_file.write(specialita)
        out_file.write("; ")
        out_file.write(primo)
        out_file.write("; ")
        out_file.write(secondo)
        out_file.write("; ")
        out_file.write(terzo)
        out_file.write("; ")
        out_file.write("TAPPA DEL SENTIERO")
        out_file.write("; ")
        out_file.write(tappa)
        out_file.write("; ")
        out_file.write(carattere)
        out_file.write("; ")
        out_file.write(salute)
        out_file.write("; ")
        out_file.write(aiuto)
        out_file.write("; ")
        out_file.close()
        fn = Label(ro, text="Salvando il file...").pack()
        sleep(1)
        exit()
    except:
        err = Label(ro, text="Qualcosa non va nella scrittura delle informazioni sul file di testo.").pack()
        err = Label(ro, text="Se non lo stai facendo, esegui il file con root: [sudo python3.7 sentiero-scout.py]").pack()
        sleep(1)
        exit()

    

ro = Tk()
ro.geometry("900x1000")
ro.title("IMPEGNI DEL SENTIERO")
a = Label(ro, text="IMPEGNI DEL SENTIERO")
a.pack()
b = Label(ro, text="Nome file:")
b.pack()
nomefilep = Entry(ro, text="")
nomefilep.pack()
c = Label(ro, text="Nome:")
c.pack()
nomep = Entry(ro)
nomep.pack()
d = Label(ro, text="Squadriglia:")
d.pack()
squadrigliap = Entry(ro)
squadrigliap.pack()
sp = Label(ro, text="\n").pack()
z = Label(ro, text="SPECIALITA'").pack()
e = Label(ro, text="Specialita':")
e.pack()
specialitap = Entry(ro,)
specialitap.pack()
f = Label(ro, text="Impegno per me stesso:")
f.pack()
primop = Entry(ro)
primop.pack()
g = Label(ro, text="Impegno per la squadriglia:")
g.pack()
secondop = Entry(ro)
secondop.pack()
h = Label(ro, text="Impegno per il reparto:")
h.pack()
terzop = Entry(ro)
terzop.pack()
sp = Label(ro, text="\n").pack()
x = Label(ro, text="TAPPA").pack()
e = Label(ro, text="Tappa della:")
e.pack()
tappap = Entry(ro,)
tappap.pack()
f = Label(ro, text="Formazione del carattere:")
f.pack()
caratterep = Entry(ro)
caratterep.pack()
g = Label(ro, text="Salute e forza fisica")
g.pack()
salutep = Entry(ro)
salutep.pack()
h = Label(ro, text="Aiuto al prossimo")
h.pack()
aiutop = Entry(ro)
aiutop.pack()
salva = Button(ro, text=" SALVA ", command=gettone)
salva.pack()
ro.mainloop()
